config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :v1 do
    resources :menu, only: :index
    namespace :api do
      resources :menu do
        collection do
          get :by_status
        end
      end
    end
  end
  namespace :admin do
    resources :positions, only: :index do
      member do
        post :move_to_next_status
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/position.rb
class Position < ApplicationRecord
  include AASM

  belongs_to :parent, class_name: 'Position', foreign_key: :parent_id, optional: true
  has_many :child_positions, class_name: 'Position', foreign_key: :parent_id, dependent: :destroy

  aasm column: 'kind' do
    state :draft, initial: :true
    state :active, :blocked

    event :active do
      transitions from: :draft, to: :active
    end

    event :blocked do
      transitions from: [:draft, :active], to: :blocked
    end

    event :draft do
      transitions from: :blocked, to: :draft
    end
  end

  def parent_name
    parent&.name
  end
end

app/controllers/admin/positions_controller.rb
class Admin::PositionsController < ApplicationController
  layout 'admin'

  def index
    q = Position.includes(:parent, :child_positions).ransack(params[:q])
    positions = q.result.order(created_at: :desc).page(params[:page]).per(10)
    render locals: {positions: positions, q: q}
  end

  def move_to_next_status
    result = current_position.send("may_#{params[:kind]}?") ? current_position.send("#{params[:kind]}!") : false
    notice = result ? 'Успешно' : 'Неверный начальный статус'
    redirect_to admin_positions_path, notice: notice
  end

  def current_position
    Position.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/v1/api/menu_controller.rb
class V1::Api::MenuController < ActionController::API

  def by_status
    menu_top = Position.where(parent_id: nil)
    menu = MenuBuilder.new.perform(menu_top, params[:kind])

    render({ json: { result:  menu.as_json }})
  end
end

app/controllers/v1/menu_controller.rb
class V1::MenuController < ApplicationController
  layout 'application'

  def index
    menu_top = Position.where(parent_id: nil)
    menu = MenuBuilder.new.perform(menu_top)
    render locals: {menu: menu}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def position_color(position)
    case position.kind
      when 'draft'
        '#FFFF00'
      when 'active'
        '#198754'
      when 'blocked'
        '#FF0000'
    end
  end

  def menu_title(item)
    content_tag(:div, style: "background-color:#{position_color(item[:parent])}") do
      item[:parent].name + menu_count(item)
    end
  end

  def menu_count(item)
    " #{item[:count]}"
  end

  def menu_children(item)
    if item[:children].any?
      content_tag :ul do
        item[:children].map do |children|
          content_tag(:li, style: "background-color:#{position_color(children[:parent])}") do
            show_menu([children])
          end
        end.compact.join('').html_safe
      end
    end
  end

  def show_menu(menu)
    menu.map do |item|
      menu_title(item) + menu_children(item).to_s
    end.join('').html_safe
  end
end

app/views/admin/positions/index.html.slim
.container
  .row
    h4
      | Список позиций меню
      p id="notice" = notice
  = search_form_for q, url: admin_positions_path, method: :get, class: 'form-control' do |f|
    .row.justify-content-md-end
      .col-md-auto
        = f.search_field :parent_name_eq, value: f.object&.parent_name_eq, label: false, placeholder: "Имя Родителя", class: "form-control"
      .col-md-auto
        = f.search_field :name_eq, value: f.object&.name_eq, label: false, placeholder: "Имя", class: "form-control"
      .col-md-auto
        = f.collection_select :kind_eq, Position.aasm.events.map(&:name), :to_s, :to_s, { include_blank: "All" },  { class: "form-select" }
      .col-md-auto
        = f.submit
  .row.justify-content-md-end
  .container
    .row
      table.table-bordered.table-striped
        thead
          tr
            th ID
            th Название
            th Статус
            th Родитель
            th Действие
        tbody
          - positions.each do |position|
            tr style="background-color:#{position_color(position)}"
              td = position.id
              td = position.name
              td = I18n.t("kinds.#{position.kind}")
              td = position.parent&.name
              td
                .container.row.justify-content-md-end
                  .col-md-auto
                    = button_to 'Активировать', move_to_next_status_admin_position_path(position.id, kind: :active), method: :post, class: 'btn-sm btn-success'
                  .col-md-auto
                    = button_to 'Новый', move_to_next_status_admin_position_path(position.id, kind: :draft), method: :post, class: 'btn-sm btn-light'
                  .col-md-auto
                    = button_to 'Блокировать', move_to_next_status_admin_position_path(position.id, kind: :blocked), method: :post, class: 'btn-sm btn-danger'

    .row
      = paginate positions, :theme => 'twitter-bootstrap-4'

app/views/layouts/admin.html.slim
doctype html
html lang="ru"
  head
    meta charset="utf-8"
      = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
      = javascript_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    body
      = yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MainMenu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/v1/menu/index.html.slim
.container
  .container #{show_menu(menu)}